[package]
name = "language-tokenizer"
version = "0.4.1"
authors = ["savannstm <savannstm@gmail.com>"]
edition = "2024"
description = "Text tokenizer for linguistic purposes, such as text matching. Supports more than 40 languages, including English, French, Russian, Japanese, Thai etc."
documentation = "https://docs.rs/language-tokenizer"
homepage = "https://crates.io/crates/language-tokenizer"
repository = "https://github.com/savannstm/language-tokenizer"
readme = "README.md"
rust-version = "1.88.0"
license = "WTFPL"
keywords = ["tokenizer", "text", "linguistic", "language", "segmenter"]
categories = ["text-processing"]
exclude = ["/.gitignore", "/.rustfmt.toml"]

[package.metadata.cargo-machete]
ignored = ["strum"]

[features]
full = [
    "southeast-asian",
    "snowball",
    "japanese-lindera",
    "chinese-lindera",
    "korean-lindera",
]

snowball = [
    "dep:waken_snowball",
    "dep:unicode-normalization",
    "dep:unicode-segmentation",
]

cjk = []
lindera = []
icu = []

japanese-lindera = ["dep:lindera", "dep:lindera-analysis", "cjk", "lindera"]
chinese-lindera = ["dep:lindera", "dep:lindera-analysis", "cjk", "lindera"]
korean-lindera = ["dep:lindera", "dep:lindera-analysis", "cjk", "lindera"]

japanese-icu = [
    "dep:icu_segmenter",
    "dep:itertools",
    "icu_segmenter/compiled_data",
    "icu_segmenter/auto",
    "cjk",
    "icu",
]
chinese-icu = [
    "dep:icu_segmenter",
    "dep:itertools",
    "icu_segmenter/compiled_data",
    "icu_segmenter/auto",
    "cjk",
    "icu",
]

japanese-lindera-embed-ipadic = [
    "japanese-lindera",
    "lindera/embed-ipadic",
    "lindera-analysis/embed-ipadic",
]
japanese-lindera-embed-ipadic-neologd = [
    "japanese-lindera",
    "lindera/embed-ipadic-neologd",
    "lindera-analysis/embed-ipadic-neologd",
]
japanese-lindera-embed-unidic = [
    "japanese-lindera",
    "lindera/embed-unidic",
    "lindera-analysis/embed-unidic",
]
chinese-lindera-embed = [
    "chinese-lindera",
    "lindera/embed-cc-cedict",
    "lindera-analysis/embed-cc-cedict",
]
korean-lindera-embed = [
    "korean-lindera",
    "lindera/embed-ko-dic",
    "lindera-analysis/embed-ko-dic",
]

southeast-asian = [
    "dep:icu_segmenter",
    "dep:itertools",
    "icu_segmenter/compiled_data",
    "icu_segmenter/lstm",
    "icu",
]

serde = ["dep:serde"]

[dependencies]
icu_segmenter = { version = "2.3.0", optional = true }
itertools = { version = "0.15.0", optional = true }
lindera = { version = "6.2.0", optional = true }
lindera-analysis = { version = "6.2.0", optional = true }
num_enum = "0.7.6"
serde = { version = "1.0.229", optional = true }
strsim = "0.11.1"
strum = { version = "0.28.0", features = ["strum_macros"] }
strum_macros = "0.28.0"
thiserror = "2.0.21"
unicode-normalization = { version = "0.1.25", optional = true }
unicode-segmentation = { version = "1.13.3", optional = true }
waken_snowball = { version = "0.1.0", optional = true }
